[tool.poetry]
name = "LightGBM_template"
version = "0.0.1"
description = ""
authors = ["Mikhail S. <fortis3000@gmail.com>"]
license = "none"
readme = "README.md"

# addung custom source causes downgrading the library versions
#[[tool.poetry.source]]
#name = "conda-forge"
#url = "https://conda.anaconda.org/conda-forge/"
#priority = "default"

# https://python-poetry.org/docs/dependency-specification/#version-constraints
[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^2.4.2"
pyyaml = "^6.0.1"

[tool.poetry.group.codestyle.dependencies]
black = "^23.10.1"
isort = "^5.12.0"
pylint = "^3.0.2"

[tool.poetry.group.dev.dependencies]
typer = "^0.9.0"
pandas = "<=2.1.2"
scikit-learn = "^1.3.2"
lightgbm = "^4.1.0"

[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'
# 'extend-exclude' excludes files or directories in addition to the defaults
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
  ^/foo.py    # exclude a file named foo.py in the root of the project
  | .*_pb2.py  # exclude autogenerated Protocol Buffer files anywhere in the project
)
'''

[tool.isort]
profile = "black"
src_paths = ["src"]
